// Registros Zehirut — lista inicial de productos de Sanidad (se agrega una sola vez, ver
// asegurarSanidad_ en Code.gs). Sale de la hoja INVENTARIO de la planilla "Inventario y stock de
// medicamentos" (30/09/2026). Después se editan desde la app (Configurar productos).
// [Producto, Rubro, Unidad, Contenido por unidad, Unidad del contenido]
const PRODUCTOS_SANIDAD = [
  ['4 x 2', 'Medicamentos', 'frasco', 1000, 'ml'],
  ['ACUPRIN', 'Medicamentos', 'frasco', 500, 'ml'],
  ['AD3E', 'Medicamentos', 'frasco', 250, 'ml'],
  ['ADAPTADOR MIN', 'Medicamentos', 'frasco', 500, 'ml'],
  ['ADAPTADOR VIT', 'Medicamentos', 'frasco', 500, 'ml'],
  ['ADE', 'Medicamentos', 'frasco', 500, 'ml'],
  ['ALCOHOL', 'Medicamentos', 'frasco', 1000, 'ml'],
  ['ALGIMINE', 'Medicamentos', 'frasco', 100, 'ml'],
  ['ANTOTOXICO', 'Medicamentos', 'frasco', 100, 'ml'],
  ['ASCINDEL PLUS 2,5L', 'Medicamentos', 'bidón', 2500, 'ml'],
  ['B12', 'Medicamentos', 'frasco', 50, 'ml'],
  ['BAGODRYL', 'Medicamentos', 'bidón', 5000, 'ml'],
  ['BAGODRYL 1L', 'Medicamentos', 'frasco', 1000, 'ml'],
  ['BERTAC', 'Medicamentos', 'frasco', 1000, 'ml'],
  ['BIOXAN', 'Medicamentos', 'frasco', 500, 'ml'],
  ['BOVISAN TOTAL 100 ml', 'Medicamentos', 'frasco', 100, 'ml'],
  ['BOVISAN TOTAL 250 ml', 'Medicamentos', 'frasco', 250, 'ml'],
  ['BUMERANG 3,15%', 'Medicamentos', 'frasco', 500, 'ml'],
  ['CIDENTAL 250 ml', 'Medicamentos', 'frasco', 250, 'ml'],
  ['CIDENTAL 500 ml', 'Medicamentos', 'frasco', 500, 'ml'],
  ['CIPERSIN', 'Medicamentos', 'bidón', 5000, 'ml'],
  ['CLOSTRISAN 11 100 ml', 'Medicamentos', 'frasco', 100, 'ml'],
  ['CLOSTRISAN 11 250 ml', 'Medicamentos', 'frasco', 250, 'ml'],
  ['COLIRIOS SPRY', 'Medicamentos', 'frasco', 125, 'ml'],
  ['COMPLEVIT', 'Medicamentos', 'frasco', 500, 'ml'],
  ['CURACEF DUO', 'Medicamentos', 'frasco', 100, 'ml'],
  ['DICLOFENACO 50', 'Medicamentos', 'frasco', 50, 'ml'],
  ['ECTOLINE', 'Medicamentos', 'bidón', 5000, 'ml'],
  ['ECTOLINE SPRY', 'Medicamentos', 'frasco', 500, 'ml'],
  ['EQUIMAX', 'Medicamentos', 'frasco', 100, 'ml'],
  ['FLOK', 'Medicamentos', 'frasco', 500, 'ml'],
  ['FOR BOX 2,5 L', 'Medicamentos', 'bidón', 2500, 'ml'],
  ['FORT UP', 'Medicamentos', 'frasco', 500, 'ml'],
  ['FORTIBIOTICO', 'Medicamentos', 'frasco', 20, 'ml'],
  ['FOSFOSAN', 'Medicamentos', 'frasco', 500, 'ml'],
  ['GALMETRIN PLUS SPRY', 'Medicamentos', 'frasco', 440, 'ml'],
  ['GALMETRIN POMADA', 'Medicamentos', 'frasco', 1000, 'ml'],
  ['GEMICIN SPRY', 'Medicamentos', 'frasco', 250, 'ml'],
  ['GUANTE LATEX', 'Medicamentos', 'caja', 100, 'un'],
  ['HEPATONIC', 'Medicamentos', 'frasco', 100, 'ml'],
  ['IMIDOGAN', 'Medicamentos', 'frasco', 100, 'ml'],
  ['IMPACTO 5L', 'Medicamentos', 'bidón', 5000, 'ml'],
  ['JERINGA DESECHABLE 10 ml', 'Medicamentos', 'unidad', '', ''],
  ['JERINGA DESECHABLE 20 ml', 'Medicamentos', 'unidad', '', ''],
  ['JERINGA DESECHABLE 3 ml', 'Medicamentos', 'unidad', '', ''],
  ['JERINGA DESECHABLE 50 ml', 'Medicamentos', 'unidad', '', ''],
  ['LEPTO 8 240 ml', 'Medicamentos', 'frasco', 240, 'ml'],
  ['LEPTO 8 45 ml', 'Medicamentos', 'frasco', 45, 'ml'],
  ['MAGNECAL PLUS', 'Medicamentos', 'frasco', 500, 'ml'],
  ['MASTER LP 4%', 'Medicamentos', 'frasco', 1000, 'ml'],
  ['MAXFLOR L.A.', 'Medicamentos', 'frasco', 50, 'ml'],
  ['MAXIBIOTIC', 'Medicamentos', 'frasco', 250, 'ml'],
  ['MEXIVER MAX 1%', 'Medicamentos', 'frasco', 500, 'ml'],
  ['MEXIVER TOP 3.15%', 'Medicamentos', 'frasco', 500, 'ml'],
  ['NEUMOSAN', 'Medicamentos', 'frasco', 250, 'ml'],
  ['NOPIETIN', 'Medicamentos', 'frasco', 500, 'ml'],
  ['OVERBIOTIC', 'Medicamentos', 'frasco', 100, 'ml'],
  ['PARAXANE', 'Medicamentos', 'frasco', 1000, 'ml'],
  ['PHARMAPRIM', 'Medicamentos', 'frasco', 100, 'ml'],
  ['POLICALCINA FORTE', 'Medicamentos', 'frasco', 500, 'ml'],
  ['RABATVAC', 'Medicamentos', 'frasco', 100, 'ml'],
  ['ROTATEC J5', 'Medicamentos', 'frasco', 120, 'ml'],
  ['SELENIE', 'Medicamentos', 'frasco', 250, 'ml'],
  ['SHOTAPEN', 'Medicamentos', 'frasco', 100, 'ml'],
  ['SKIPPER', 'Medicamentos', 'frasco', 500, 'ml'],
  ['SOROVITA COMPLEX', 'Medicamentos', 'frasco', 500, 'ml'],
  ['STAND UP', 'Medicamentos', 'frasco', 100, 'ml'],
  ['SUIFERRO FUERTE', 'Medicamentos', 'frasco', 50, 'ml'],
  ['SUPLENUT', 'Medicamentos', 'frasco', 500, 'ml'],
  ['SUPRATICK', 'Medicamentos', 'frasco', 1000, 'ml'],
  ['TINTURA DE YODO', 'Medicamentos', 'frasco', 1000, 'ml'],
  ['TRISTEZINA', 'Medicamentos', 'frasco', 20, 'ml'],
  ['UMBICURA', 'Medicamentos', 'frasco', 250, 'ml'],
  ['VERRUGAL', 'Medicamentos', 'frasco', 20, 'ml'],
  ['ZUPREVO', 'Medicamentos', 'frasco', 100, 'ml'],
  ['ZURONTOP', 'Medicamentos', 'bidón', 5000, 'ml'],
  ['APLICADOR DIB', 'Insumos IATF', 'unidad', '', ''],
  ['BIOESTROGEN', 'Insumos IATF', 'frasco', 100, 'ml'],
  ['BURESELINA', 'Insumos IATF', 'frasco', 50, 'ml'],
  ['CRONI-CIP', 'Insumos IATF', 'frasco', 100, 'ml'],
  ['ECEGON 100 ml', 'Insumos IATF', 'frasco', 100, 'ml'],
  ['ECEGON 20 ml', 'Insumos IATF', 'frasco', 20, 'ml'],
  ['ENZAPROST 100 ml', 'Insumos IATF', 'frasco', 100, 'ml'],
  ['ENZAPROST 20 ml', 'Insumos IATF', 'frasco', 20, 'ml'],
  ['GONAXAL', 'Insumos IATF', 'frasco', 50, 'ml'],
  ['GUANTE DE TACTO', 'Insumos IATF', 'caja', 100, 'un'],
  ['PROGESTAR (DISPOSITIVO)', 'Insumos IATF', 'caja', 10, 'un'],
  ['VAINAS', 'Insumos IATF', 'unidad', '', ''],
  ['SEMEN BN LEBRON', 'Semen', 'pajuela', '', ''],
  ['SEMEN BR BAQUEANO', 'Semen', 'pajuela', '', ''],
  ['SEMEN BR CAPITANEJO', 'Semen', 'pajuela', '', ''],
  ['SEMEN BR EFICIENTE', 'Semen', 'pajuela', '', ''],
  ['SEMEN BR MATE', 'Semen', 'pajuela', '', ''],
  ['SEMEN BR PROFESOR', 'Semen', 'pajuela', '', ''],
  ['SEMEN BR RON', 'Semen', 'pajuela', '', ''],
  ['SEMEN MISSOURI BR', 'Semen', 'pajuela', '', ''],
  ['SEMEN RA BORAN', 'Semen', 'pajuela', '', ''],
  ['SEMEN ROBUSTO BN', 'Semen', 'pajuela', '', ''],
];
